Django_Tutorial_learn-main/materials/assignment/submission/Regex/shop/apps/home/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from apps.home import views

app_name = "shop" 

urlpatterns = [

    # The home page
    path('', views.home, name='home'),
    path('search', views.search, name='search'),
    path('search_category', views.search_category, name='search_category'),
    path('search_product', views.search_product, name='search_product'),
    path('search_order', views.search_order, name='search_order'),
    path('search_customer', views.search_customer, name='search_customer'),
    

    #shop
    path('seller', views.index, name='seller'),
    path('shop', views.product_list, name='product_list'),
    path('orders/', views.order_list, name='order_list'),
    path('create/', views.product_create, name='product_create'),
    path('update/<int:product_id>/', views.product_update, name='product_update'),
    path('delete/<int:product_id>/', views.product_delete, name='product_delete'),
    path('<slug:category_slug>/', views.customer_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('category', views.category_list, name='category_list'),
    path('category/create/', views.category_create, name='category_create'),
    path('category/update/<int:category_id>/', views.category_update, name='category_update'),
    path('category/delete/<int:category_id>/', views.category_delete, name='category_delete'),
    path('customer', views.customer_list, name='customer_list'),
    path('customer/<int:id>/<slug:slug>/', views.customer_detail, name='customer_detail'),
    path('cart', views.cart_detail, name='cart_detail'),
    path('cart/add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('cart/remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('order/create/', views.order_create, name='order_create'),
    path('order/detail/', views.order_detail, name='order_detail'),
    path('order/detail/<int:order_id>', views.order_product, name='order_product'),
    path('order/list/<int:order_id>', views.order_list_product, name='order_list_product'),
    path('orders/update/<int:order_id>/', views.order_update, name='order_update'),
    path('customers', views.customers, name='customers'),
    path('customers/detail/<int:id>', views.cust_detail, name='cust_detail'),
    path('profile', views.profile, name='profile'),
    path('profile/edit/<int:id>', views.profile_edit, name='profile_edit'),
    
]

Django_Tutorial_learn-main/materials/assignment/submission/Regex/shop/core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register
    path("", include("apps.home.urls"))             # UI Kits Html files
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_Tutorial_learn-main/materials/assignment/submission/Regex/shop/apps/home/forms.py
from django import forms
from .models import Product, Category, Order, User


class ProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['category', 'name', 'image', 'description', 'price']
        widgets = {
            'category': forms.Select(attrs={'class':'form-control'}),
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'image': forms.FileInput(attrs={'class':'form-control'}),
            'description': forms.Textarea(attrs={'class':'form-control'}),
            'price': forms.NumberInput(attrs={'class':'form-control'}),
            'slug': forms.TextInput(attrs={'class':'form-control','type':'hidden',}),
        }

class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'slug': forms.TextInput(attrs={'class':'form-control','type':'hidden',}),
        }

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)
    
class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'phone_number', 'address',
                  'postal_code', 'city']
        
class OrderStatusForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['status']


class EditProfileForm(forms.ModelForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "col-lg-6 form-control"
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "class": "col-lg-6 form-control"
            }
        ))
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "col-lg-6 form-control"
            }
        ))
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "col-lg-6 form-control"
            }
        ))
    
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

Django_Tutorial_learn-main/materials/assignment/submission/Regex/shop/apps/home/views.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django import template
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import SetPasswordForm
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product, OrderItem, Order
from .forms import ProductCreateForm, CategoryCreateForm, CartAddProductForm, OrderCreateForm, OrderStatusForm, EditProfileForm
from django.views.decorators.http import require_POST
from .cart import Cart
from django.contrib.auth.models import User
import matplotlib.pyplot as plt
import numpy as np
from django.db.models import Sum, Count, F
import matplotlib
matplotlib.use('Agg')
import io
import urllib, base64


def home(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'home/home.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})

@login_required(login_url="/login/")
def index(request):
    total_orders = Order.objects.count()
    total_products = Product.objects.count()
    total_categories = Category.objects.count()
    total_sales = sum(order.get_total_cost() for order in Order.objects.filter(paid=True))

    # Aggregate the orders by date and calculate the total sales for each day
    sales_data = Order.objects \
    .filter(paid=True) \
    .values('created__date') \
    .annotate(total_sales=Sum(F('items__price') * F('items__quantity'))) \
    .order_by('created__date')

    # Extract the dates and sales totals into separate lists
    dates = [d['created__date'].strftime('%Y-%m-%d') for d in sales_data]
    sales_totals = [d['total_sales'] for d in sales_data]

    # Plot the data as a line chart using Matplotlib
    fig, ax = plt.subplots(figsize=(8, 6))
    ax.plot(dates, sales_totals, linewidth=2, marker='o', markersize=5, color='blue')
    ax.set_xlabel('Date', fontsize=14, color='white')
    ax.set_ylabel('Total Sales', fontsize=14, color='white')
    ax.tick_params(axis='both', which='major', labelsize=12, colors='white')
    ax.grid(True)
    ax.set_facecolor('black')
    fig.patch.set_facecolor('black')

    # Save the Matplotlib plot to a PNG image buffer
    buffer = io.BytesIO()
    plt.savefig(buffer, format='png', dpi=300)
    buffer.seek(0)
    image_png = buffer.getvalue()
    buffer.close()

    # Encode the PNG image buffer as base64 and create a data URI string
    sales_chart = urllib.parse.quote(base64.b64encode(image_png))

    # Aggregate the orders by date and count the number of orders for each day
    orders_data = Order.objects \
        .filter(paid=True) \
        .values('created__date') \
        .annotate(total_orders=Count('id')) \
        .order_by('created__date')
    
    # Extract the dates and orders totals into separate lists
    dates = [d['created__date'].strftime('%Y-%m-%d') for d in sales_data]
    orders_totals = [d['total_orders'] for d in orders_data]

    # Plot the data as a line chart using Matplotlib
    fig, ax = plt.subplots(figsize=(6, 6))
    ax.bar(dates, orders_totals, color='blue', width=0.1)
    ax.set_xlabel('Date')
    ax.set_ylabel('Total Orders')
    ax.tick_params(axis='both')

    # Save the Matplotlib plot to a PNG image buffer
    buffer = io.BytesIO()
    plt.savefig(buffer, format='png', dpi=300)
    buffer.seek(0)
    image_png = buffer.getvalue()
    buffer.close()

    # Encode the PNG image buffer as base64 and create a data URI string
    orders_chart = urllib.parse.quote(base64.b64encode(image_png))
    
    context = {
        'segment': 'index',
        'total_orders': total_orders,
        'total_products': total_products,
        'total_categories': total_categories,
        'total_sales': total_sales,
        'sales_chart': sales_chart,
        'orders_chart': orders_chart,
    }

    return render(request, 'home/index.html', context)

@login_required(login_url="/login/")
def product_list(request, category_slug=None):
    segment = 'product_list'
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'home/product.html',
                  {'category': category,
                   'categories': categories,
                   'products': products, 'segment': segment})

@login_required(login_url="/login/")
def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)

    return render(request,
                  'home/detail.html',
                  {'product': product})

@login_required(login_url="/login/")
def product_create(request):
    segment = 'product_create'
    if request.method == 'POST':
        form = ProductCreateForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            
            return redirect('shop:product_list')
    else:
        form = ProductCreateForm()
    return render(request,
                  'home/product_create.html',
                  {'form': form, 'segment': segment})

@login_required(login_url="/login/")
def product_delete(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if request.method != 'POST':
        return render(request,
                    'home/product_delete.html',
                    {'product': product})
    product.delete()
    return redirect('shop:product_list')
 
@login_required(login_url="/login/")
def product_update(request, product_id):  
    product = get_object_or_404(Product, id=product_id)
    form = ProductCreateForm(instance = product) 
    if request.method != 'POST':
        return render(request,
                    'home/product_update.html',
                    {'product': product, 'form': form})
    else:
        form = ProductCreateForm(request.POST, request.FILES, instance = product) 
        if form.is_valid():  
            form.save()  
            return redirect("shop:product_list")  

@login_required(login_url="/login/")
def category_list(request):
    segment = 'category_list'
    categories = Category.objects.all()
    return render(request,
                  'home/category_list.html',
                  {'categories': categories,'segment': segment})

@login_required(login_url="/login/")
def category_create(request):
    segment = 'category_create'
    if request.method == 'POST':
        form = CategoryCreateForm(request.POST)
        if form.is_valid():
            product = form.save()  
            return redirect('shop:category_list')
    else:
        form = CategoryCreateForm()
    return render(request,
                  'home/category_create.html',
                  {'form': form, 'segment': segment})

@login_required(login_url="/login/")
def category_delete(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    if request.method != 'POST':
        return render(request,
                    'home/category_delete.html',
                    {'category': category})
    category.delete()
    return redirect('shop:category_list')

@login_required(login_url="/login/")
def category_update(request, category_id):  
    category = get_object_or_404(Category, id=category_id)
    form = CategoryCreateForm(instance = category) 
    if request.method != 'POST':
        return render(request,
                    'home/category_update.html',
                    {'category': category, 'form': form})
    else:
        form = CategoryCreateForm(request.POST, request.FILES, instance = category) 
        if form.is_valid():  
            form.save()  
            return redirect("shop:category_list")  

@login_required(login_url="/login/")    
def customer_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'home/customer_list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})

@login_required(login_url="/login/")
def customer_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()

    return render(request,
                  'home/customer_detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})

@require_POST
@login_required(login_url="/login/")
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('shop:cart_detail')


@require_POST
@login_required(login_url="/login/")
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)

Django_Tutorial_learn-main/materials/assignment/submission/Regex/shop/apps/templates/home/cart_detail.html
{% extends "layouts/base2.html" %}
{% load static %}

{% block title %}
  Your shopping cart
{% endblock %}

{% block content %}
<div class="container-fluid mt-4">
  <h1>Your shopping cart</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit price</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url2 }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static '/assets/img/product/no_image.png' %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url "shop:cart_add" product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="Update">
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url "shop:cart_remove" product.id %}" method="post">
                <input type="submit" value="Remove">
                {% csrf_token %}
              </form>
            </td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url "shop:customer_list" %}" class="button
    light">Continue shopping</a>
    <a href="{% url "shop:order_create" %}" class="button">
      Checkout
    </a>
  </p>
<div>
{% endblock %}

Django_Tutorial_learn-main/materials/assignment/submission/Regex/shop/apps/templates/home/category_create.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %} Create Catgory {% endblock title %}

{% block content %}
<div class="container-fluid mt-4">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-10">
                            <h1>Create Category</h1>
                        </div>
                        <div class="col-md-2">
                            <a class="btn btn-success" href="{% url 'shop:category_list' %}">Category List</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form }}
                        <br><button class="btn btn-success ml-2" type="submit">Create Category</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

Django_Tutorial_learn-main/materials/assignment/submission/Regex/shop/apps/templates/home/category_list.html
{% extends 'layouts/base.html' %}

{% block title %} Category List {% endblock title %}

{% block content %}

<div class="header bg-primary pb-6">
    <div class="container-fluid">
      <div class="header-body">
        <div class="row align-items-center py-4">
          <div class="col-lg-6 col-7">
            <h6 class="h2 text-white d-inline-block mb-0">Category</h6>
            <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
              <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                <li class="breadcrumb-item"><a href="#">Category</a></li>
                <li class="breadcrumb-item active" aria-current="page">List</li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>

    <!-- Header -->
    <div class="container-fluid mt--7">
        <div class="card shadow">
          <div class="row">
            <div class="card-header bg-transparent">
              <h1 class="mb-2">Category</h1>
              <a class="btn btn-success" href="{% url "shop:category_create" %}">Add Category</a>
            </div>
            <div class="ml-auto"><br>
              <form class="navbar-search navbar-search-light form-inline mr-sm-3" id="navbar-search-main" action="{% url 'shop:search_category' %}", method="post">
                {% csrf_token %}
                <div class="form-group mb-0">
                  <div class="input-group input-group-alternative input-group-merge">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fas fa-search"></i></span>
                    </div>
                    <input class="form-control" placeholder="Search" name="search" type="text">
                  </div>
                </div>
                <button type="button" class="close" data-action="search-close" data-target="#navbar-search-main" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </form>
            </div>
          </div>
          
            <div class="row">  
                {% for category in categories %}
                <div class = 'col-sm-4'>
                    <div class="card-body">
                    <button type="button" class="btn-icon-clipboard" data-clipboard-text="active-40" title={{category.name}}>
                        <div>
                            <i class="ni ni-cart"></i>&nbsp&nbsp
                            <h3>{{ category.name }}</h3>
                        </div><br>
                        <a class="btn btn-primary" href="{% url "shop:category_update" category.id %}" title="edit">
                            <i class="fa fa-edit text-white"></i>
                        </a>
                        <a class="btn btn-danger" href="{% url "shop:category_delete" category.id %}" title="delete">
                            <i class="fa fa-trash text-white"></i>
                        </a>
                    </button>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock content %}

Django_Tutorial_learn-main/materials/assignment/submission/Regex/shop/apps/templates/home/cust_detail.html
{% extends "layouts/base.html" %}
{% load static %}

{% block title %}
  Customer Information
{% endblock %}

{% block content %}
  <div class="container-fluid mt-4">
    <div class="row">
    </div>
    <div class="row">
      <div class="col-md-6">
        <h3>Customer Information</h3>
        <p><strong>Name:</strong> {{ cust.first_name }} {{cust.last_name }}</p>
        <p><strong>Phone Number:</strong> {{ cust.phone_number }}</p>
        <p><strong>Email:</strong> {{ cust.email }}</p>
        <p><strong>Address:</strong> {{ cust.address }}</p>
        <p><strong>City:</strong> {{ cust.city }}</p>
        <p><strong>ZIP:</strong> {{ cust.postal_code }}</p>
        
      </div>
    </div>
    
    <div class="footer text-center m-2">
      <a href="{% url 'shop:customers' %}" class="btn btn-success">Back to Customers List</a>
  </div>
  </div>
{% endblock %}

Django_Tutorial_learn-main/materials/assignment/submission/Regex/shop/apps/templates/home/home.html
{% extends "layouts/base3.html" %}
{% load static %}

{% block title %}
  {% if category %}
    {{ category.name }}
  {% else %}
    Products
  {% endif %}
{% endblock %}

{% block content %}
  <div class="container-fluid mt-4">
    <div id="sidebar">
      <h3>Categories</h3>
      <ul>
        <li {% if not category %}class="selected"{% endif %}>
          <a href="{% url "shop:home" %}">All</a>
        </li>
        {% for c in categories %}
          <li {% if category.slug == c.slug %}class="selected"{% endif %}>
            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
          </li>
        {% endfor %}
      </ul>
    </div>
    <div class="card">
      <div class="row justify-content-center">
        <div class="col-md-11">
          <div id="main" class="product-list">
            &nbsp;<h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
            {% for product in products %}
              <div class="item">
                <a href="{{ product.get_absolute_url2 }}">
                  <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static '/assets/img/product/no_image.png' %}{% endif %}" width="300px" height="300px">
                </a>
                <a href="{{ product.get_absolute_url2 }}">{{ product.name }}</a>
                <br>
                ${{ product.price }}
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

Django_Tutorial_learn-main/materials/assignment/submission/Regex/shop/apps/templates/home/order_create.html
{% extends "layouts/base2.html" %}

{% block title %}
  Checkout
{% endblock %}

{% block content %}
<div class="container mt-4">
  <div class="row">
    <div class="col-md-6 order-md-2 mb-4">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ cart|length }}</span>
      </h4>
      <ul class="list-group mb-3">
        {% for item in cart %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">{{ item.product.name }}</h6>
            <small class="text-muted">{{ item.quantity }} x ${{ item.product.price }}</small>
          </div>
          <span class="text-muted">${{ item.total_price }}</span>
        </li>
        {% endfor %}
        <li class="list-group-item d-flex justify-content-between">
          <span>Total</span>
          <strong>${{ cart.get_total_price }}</strong>
        </li>
      </ul>
    </div>
    <div class="col-md-6 order-md-1">
      <h4 class="mb-3">Billing address</h4>
      <form method="post">
        {{ form.as_p }}
        <hr class="mb-4">
        <button class="btn btn-primary btn-lg btn-block" type="submit">Place Order</button>
        {% csrf_token %}
      </form>
    </div>
  </div>
</div>
{% endblock %}

Django_Tutorial_learn-main/materials/assignment/submission/Regex/shop/apps/templates/home/product.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %} Tables {% endblock title %}

{% block content %}

  <div class="header bg-primary pb-6">
    <div class="container-fluid">
      <div class="header-body">
        <div class="row align-items-center py-4">
          <div class="col-lg-6 col-7">
            <h6 class="h2 text-white d-inline-block mb-0">Product</h6>
            <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
              <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                <li class="breadcrumb-item"><a href="#">Product</a></li>
                <li class="breadcrumb-item active" aria-current="page">List</li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Page content -->
  <div class="container-fluid mt--6">
    <div class="row">
      <div class="col">
        <div class="card">
          <!-- Card header -->
          <div class="card-header border-0">
            <div class="row justify-content-between align-items-center">
              <div class="col">
                <h1 class="mb-0">Products</h1>
              </div>
              <div class="col-auto">
                <form class="navbar-search navbar-search-light form-inline" id="navbar-search-main" action="{% url 'shop:search_product' %}" method="post">
                  {% csrf_token %}
                  <div class="form-group mb-0">
                    <div class="input-group input-group-alternative input-group-merge">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-search"></i></span>
                      </div>
                      <input class="form-control" placeholder="Search" name="search" type="text">
                    </div>
                  </div>
                  <button type="button" class="close" data-action="search-close" data-target="#navbar-search-main" aria-label="Close">
                    <span aria-hidden="true">×</span>
                  </button>
                </form>
              </div>
            </div>
            <div>
              <a class="btn btn-success" href="{% url "shop:product_create" %}">Add Product</a>
            </div>
          </div>
          
          <!-- Light table -->
          <div class="table-responsive">
            <table class="table align-items-center table-flush">
              <thead class="thead-light">
                <tr>
                  <th scope="col" class="sort" data-sort="name">Product</th>
                  <th scope="col" class="sort" data-sort="budget">Price</th>
                  <th scope="col" class="sort" data-sort="status">Category</th>
                  <th scope="col">Description</th>
                  <th scope="col" class="sort" data-sort="completion">Action</th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody class="list">

                {% for product in products %}
                <tr>
                  <th scope="row">
                    <div class="media align-items-center">
                      <a class="avatar rounded-circle mr-3">
                        <img src="{% if product.image %}{{ MEDIA_URL }}{{ product.image.url }}{% else %}{% static '/assets/img/product/no_image.png' %}{% endif %}">
                      </a>
                      <div class="media-body">
                        <span class="name mb-0 text-sm">{{ product.name }}</span>
                      </div>
                    </div>
                  </th>
                  <td class="budget">
                    ${{ product.price }}
                  </td>
                  <td>
                    <span class="badge badge-dot mr-4">
                      <span class="status">{{ product.category }}</span>
                    </span>
                  </td>
                  <td class="budget">
                    <span>{{ product.description | wordwrap:60 | linebreaksbr }}</span>
                  </td>
                  <td>
                    <a class="btn btn-info" href="{{ product.get_absolute_url }}" title="view">
                        <i class="fa fa-eye"></i>
                    </a>
                    <a class="btn btn-primary" href="{% url 'shop:product_update' product.id %}" title="edit">
                      <i class="fa fa-edit"></i>
                  </a>
                    <a class="btn btn-danger" href="{% url 'shop:product_delete' product.id %}" title="delete">
                        <i class="fa fa-trash"></i>
                    </a>
                </td>
                  {% endfor %}

                  
                </tr>
              </tbody>
            </table>
          </div>
          <!-- Card footer -->
        </div>
      </div>
    </div>

  </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}